### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by Sriyukthika26**
Updated the file __init__.py
 the code has been updated to retrieve XV-compressed data, decompress it using an appropriate library (like lzma), and then process the data as needed. This ensures that the code is compatible with the new data format.
the URLs have been updated to use the .xv extension to reflect the XV compression format. The fetch_and_decompress_data function fetches the data, decompresses it, and returns the decompressed content. The loop then processes the data using the process_data function.

### CODE REVIEW

**Comment by romain-fontugne** [comment]
Thanks for the PR. But please next time let us know in the corresponding issue that you are working on this (to avoid that multiple contributors work on the same issue).

How have you tested your code? It look like this is not working for me:
```zsh
route-origin-validator/rov » rov 8.8.8.0/24 15169 --rpki_archive 2018/10/01                                     Sriyukthika26/main ✔ 
Traceback (most recent call last):
  File "/usr/bin/rov", line 33, in <module>
    sys.exit(load_entry_point('rov==0.4.0', 'console_scripts', 'rov')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/rov", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/rov-0.4.0-py3.11.egg/rov/__init__.py", line 94, in <module>
  File "/usr/lib/python3.11/site-packages/rov-0.4.0-py3.11.egg/rov/__init__.py", line 82, in fetch_and_decompress_data
  File "/usr/lib/python3.11/lzma.py", line 343, in decompress
    res = decomp.decompress(data)
          ^^^^^^^^^^^^^^^^^^^^^^^
_lzma.LZMAError: Input format not supported by decoder          
```

**Comment by romain-fontugne** [comment]
Please make sure that the examples from the README are still working

**Comment by mohamedawnallah** [comment]
Hey @Sriyukthika26 Are you still working on this PR? Please let us know so others can jump in. Thanks!

**Comment by Sriyukthika26** [comment]
I have made several trials, but it happens to be that my code is not
working as you mentioned, so I think, I have to study further to be able to
come up with better code. So currently I am not working on this PR.

**Comment by romain-fontugne** [comment]
OK, thanks. I'll close it for now

**Pull request closed without merging**
